workflows:
  flutter-workflow:
    name: Flutter Workflow
    working_directory: frontend
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build APK
        script: flutter build apk --release
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - sethchangcom@gmail.com
