// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeTtQQW-tgbFgDKwt5_scQ0jXIg_cGqSA',
    appId: '1:847075157501:web:526d795145bf0fdb6a6594',
    messagingSenderId: '847075157501',
    projectId: 'gemini-app-ba066',
    authDomain: 'gemini-app-ba066.firebaseapp.com',
    storageBucket: 'gemini-app-ba066.appspot.com',
    measurementId: 'G-XDHPGN626M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcIhwoUCAlp2Zo9_RkBC_Ml_FpRdYqYe0',
    appId: '1:847075157501:android:ca5f0562cb1a5e7e6a6594',
    messagingSenderId: '847075157501',
    projectId: 'gemini-app-ba066',
    storageBucket: 'gemini-app-ba066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEXSrf7vvMnfD5kZX91jpsa2OV1pb8GVw',
    appId: '1:847075157501:ios:f2aaa245c9d1076a6a6594',
    messagingSenderId: '847075157501',
    projectId: 'gemini-app-ba066',
    storageBucket: 'gemini-app-ba066.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEXSrf7vvMnfD5kZX91jpsa2OV1pb8GVw',
    appId: '1:847075157501:ios:f2aaa245c9d1076a6a6594',
    messagingSenderId: '847075157501',
    projectId: 'gemini-app-ba066',
    storageBucket: 'gemini-app-ba066.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeTtQQW-tgbFgDKwt5_scQ0jXIg_cGqSA',
    appId: '1:847075157501:web:662c9bde88f2752a6a6594',
    messagingSenderId: '847075157501',
    projectId: 'gemini-app-ba066',
    authDomain: 'gemini-app-ba066.firebaseapp.com',
    storageBucket: 'gemini-app-ba066.appspot.com',
    measurementId: 'G-8ZVTJ471MZ',
  );

}