// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6qD1XQZ4xY4PcQQkqGY4TuEdXYFP69ac',
    appId: '1:619295303737:web:46478d292d9cfa614785e8',
    messagingSenderId: '619295303737',
    projectId: 'gemini-app-428709',
    authDomain: 'gemini-app-428709.firebaseapp.com',
    storageBucket: 'gemini-app-428709.appspot.com',
    measurementId: 'G-WSY2NW7BYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOdojRnGkh84ruoudo4s4zUUajo9PD_yY',
    appId: '1:619295303737:android:8122a9ab062fc1454785e8',
    messagingSenderId: '619295303737',
    projectId: 'gemini-app-428709',
    storageBucket: 'gemini-app-428709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBThPmlC0_pdWRkXRUClnOFZloCBR5UUDs',
    appId: '1:619295303737:ios:3ac3bf9daa30d9ea4785e8',
    messagingSenderId: '619295303737',
    projectId: 'gemini-app-428709',
    storageBucket: 'gemini-app-428709.appspot.com',
    iosClientId: '619295303737-8p7sratgt116429uo4tgig6pib3q7vr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBThPmlC0_pdWRkXRUClnOFZloCBR5UUDs',
    appId: '1:619295303737:ios:3ac3bf9daa30d9ea4785e8',
    messagingSenderId: '619295303737',
    projectId: 'gemini-app-428709',
    storageBucket: 'gemini-app-428709.appspot.com',
    iosClientId: '619295303737-8p7sratgt116429uo4tgig6pib3q7vr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6qD1XQZ4xY4PcQQkqGY4TuEdXYFP69ac',
    appId: '1:619295303737:web:95248f817b6d0e134785e8',
    messagingSenderId: '619295303737',
    projectId: 'gemini-app-428709',
    authDomain: 'gemini-app-428709.firebaseapp.com',
    storageBucket: 'gemini-app-428709.appspot.com',
    measurementId: 'G-G38TP0N71V',
  );
}
